"""init schema

Revision ID: 42f58ac4d705
Revises: 95b1010512ea
Create Date: 2025-12-17 12:15:21.247636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42f58ac4d705'
down_revision: Union[str, Sequence[str], None] = '95b1010512ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('tenant_customer_id', sa.BigInteger(), nullable=False))
    op.add_column('bookings', sa.Column('time_slot_id', sa.BigInteger(), nullable=False))
    op.create_unique_constraint('uq_booking_per_tenant_slot', 'bookings', ['tenant_id', 'time_slot_id'])
    op.drop_constraint(op.f('bookings_timeslot_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_constraint(op.f('bookings_customer_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'time_slots', ['time_slot_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'bookings', 'tenant_customers', ['tenant_customer_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('bookings', 'customer_id')
    op.drop_column('bookings', 'timeslot_id')
    op.alter_column('tenants', 'plan',
               existing_type=postgresql.ENUM('LITE', 'STANDARD', 'PRO', name='tenants_plan_enum'),
               server_default='LITE',
               existing_nullable=False)
    op.alter_column('tenants', 'timezone',
               existing_type=sa.VARCHAR(length=64),
               server_default='UTC',
               existing_nullable=False)
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.create_unique_constraint(None, 'users', ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.alter_column('tenants', 'timezone',
               existing_type=sa.VARCHAR(length=64),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tenants', 'plan',
               existing_type=postgresql.ENUM('LITE', 'STANDARD', 'PRO', name='tenants_plan_enum'),
               server_default=None,
               existing_nullable=False)
    op.add_column('bookings', sa.Column('timeslot_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('customer_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_customer_id_fkey'), 'bookings', 'customers', ['customer_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('bookings_timeslot_id_fkey'), 'bookings', 'time_slots', ['timeslot_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('uq_booking_per_tenant_slot', 'bookings', type_='unique')
    op.drop_column('bookings', 'time_slot_id')
    op.drop_column('bookings', 'tenant_customer_id')
    # ### end Alembic commands ###
